/**
 * WhatsAppNotifier — Agent 6
 * Sends daily briefings and draft approval requests via Twilio WhatsApp Business API.
 * Writes pending approval state to /drafts/ for webhook handling.
 */

import 'dotenv/config';
import twilio from 'twilio';
import { info, success, warn, error } from '../skills/logger.js';
import { updateDraft } from '../skills/storage.js';

const AGENT = 'whatsappNotifier';

let _client = null;
function getTwilio() {
  if (!_client) {
    const sid = process.env.TWILIO_ACCOUNT_SID;
    const token = process.env.TWILIO_AUTH_TOKEN;
    if (!sid || !token) throw new Error('TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN must be set');
    _client = twilio(sid, token);
  }
  return _client;
}

function getAESTDate() {
  return new Date().toLocaleDateString('en-AU', {
    timeZone: 'Australia/Sydney',
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

export async function sendDailyBriefing(strategyOutput, drafts) {
  info(AGENT, 'Preparing daily briefing WhatsApp message');

  const picks = strategyOutput.topPicks.slice(0, 3);
  const dateStr = getAESTDate();

  const numberEmojis = ['1️⃣', '2️⃣', '3️⃣'];
  const pickLines = picks.map((p, i) => `${numberEmojis[i]} *${p.title}*
   Style: ${p.postStyle} — ${p.postStyleName}
   Why today: ${p.whyNow}
   Confidence: ${p.confidenceScore}/10`).join('\n\n');

  const message = `🌅 *LinkedIn Brief — ${dateStr}*

📊 *Top 3 Topic Options for Today:*

${pickLines}

Reply with *1*, *2*, *3*, or *SKIP* to continue.`;

  await sendMessage(message);

  const briefingState = {
    type: 'BRIEFING',
    picks,
    drafts: drafts.map((d) => ({ id: d.id, rank: d.pick?.rank })),
    sentAt: new Date().toISOString(),
    awaitingResponse: true,
    webhookKey: `briefing_${Date.now()}`,
  };

  info(AGENT, 'Daily briefing sent', { picks: picks.length });
  return briefingState;
}

export async function sendDraftForApproval(draft) {
  info(AGENT, `Sending draft for approval: ${draft.id}`);

  const postTitle = draft.pick?.title || 'Today\'s Post';
  const timeAEST = draft.pick?.suggestedTimeAEST || '08:00';
  const imageNote = draft.imageRecommended
    ? `📸 Image: Yes — ${draft.imageDescription || 'Generated by AI'}`
    : '📸 Image: No';

  const message = `✍️ *Draft Post — ${postTitle}*

${draft.postCopy}

${imageNote}
⏰ Suggested post time: ${timeAEST} AEST

Reply *APPROVE*, *EDIT: [your notes]*, or *DISCARD*`;

  if (message.length > 4096) {
    warn(AGENT, 'Message exceeds WhatsApp limit — truncating post copy');
    const truncated = draft.postCopy.slice(0, 1000) + '...[truncated]';
    const shortMessage = `✍️ *Draft Post — ${postTitle}*\n\n${truncated}\n\n${imageNote}\n⏰ ${timeAEST} AEST\n\nReply *APPROVE*, *EDIT: [notes]*, or *DISCARD*`;
    await sendMessage(shortMessage);
  } else {
    await sendMessage(message);
  }

  updateDraft(draft.id, { status: 'PENDING_APPROVAL', notifiedAt: new Date().toISOString() });
  success(AGENT, 'Draft sent to Victor for approval', { draftId: draft.id });
  return { draftId: draft.id, sentAt: new Date().toISOString() };
}

export async function sendAuditSummary(auditReport) {
  info(AGENT, 'Sending weekly audit summary');

  const { weekSummary: s } = auditReport;
  const message = `📊 *Weekly LinkedIn Audit — ${auditReport.period}*

📝 Posts completed: ${s.postsCompleted}
✅ Approved: ${s.approved}
❌ Rejected: ${s.rejected}
⏭ Skipped: ${s.skipped}
🔁 Rewrites: ${s.rewrites}
⚠️ API errors: ${s.apiErrors}

*Top recommendation:*
${auditReport.recommendations?.[0] || 'No recommendations this week.'}

Full report saved to /logs/ 📁`;

  await sendMessage(message);
  success(AGENT, 'Audit summary sent');
}

export async function sendMessage(body) {
  const from = process.env.TWILIO_WHATSAPP_FROM;
  const to = process.env.VICTOR_WHATSAPP_TO;

  if (!from || !to) {
    warn(AGENT, 'WhatsApp credentials not configured — logging message instead');
    console.log('\n─── WhatsApp Message (not sent) ───\n' + body + '\n───────────────────────────────\n');
    return;
  }

  if (process.env.DRY_RUN === 'true') {
    info(AGENT, '[DRY_RUN] WhatsApp message not sent');
    console.log('\n─── [DRY_RUN] WhatsApp Message ───\n' + body + '\n───────────────────────────────\n');
    return;
  }

  try {
    const msg = await getTwilio().messages.create({ from, to, body });
    info(AGENT, `Message sent: ${msg.sid}`);
    return msg.sid;
  } catch (err) {
    error(AGENT, `Failed to send WhatsApp message: ${err.message}`);
    throw err;
  }
}

if (process.argv[1].endsWith('whatsappNotifier.js')) {
  const mockStrategy = {
    topPicks: [
      { rank: 1, title: 'RBA holds rates — what it means for NFP budgets', postStyle: 'B', postStyleName: 'NEWS COMMENTARY', whyNow: 'RBA met yesterday', confidenceScore: 9 },
      { rank: 2, title: '3 Power BI tricks that saved 4 hours this week', postStyle: 'C', postStyleName: 'HOW-TO / TIPS', whyNow: 'Evergreen but highly shared', confidenceScore: 7 },
      { rank: 3, title: 'Why most finance teams misread their own dashboards', postStyle: 'H', postStyleName: 'CONTRARIAN TAKE', whyNow: 'Growing conversation on data literacy', confidenceScore: 8 },
    ],
  };
  sendDailyBriefing(mockStrategy, []).then((state) => {
    console.log('Briefing state:', state);
  }).catch(console.error);
}
