export const POST_FORMATS = {
  A: {
    code: 'A',
    name: 'INSIGHT POST',
    description: 'Share a sharp professional observation in finance, BI, or leadership',
    structure: ['Hook — a striking observation or counterintuitive truth',
      'Context — why this matters now',
      'Insight — your specific professional take',
      'So what — the implication for the reader'],
    bestFor: ['finance trends', 'BI observations', 'professional lessons'],
    engagementMechanism: 'Readers share because the insight reframes something they believed',
  },
  B: {
    code: 'B',
    name: 'NEWS COMMENTARY',
    description: "React to a real news item with Victor's professional lens",
    structure: ['News hook — state the news briefly',
      'The angle most people miss',
      "Victor's professional interpretation",
      'What finance/NFP/BI readers should do about it'],
    bestFor: ['RBA decisions', 'budget announcements', 'major policy changes'],
    engagementMechanism: 'Timeliness + expert filter = saves readers from reading the whole article',
  },
  C: {
    code: 'C',
    name: 'HOW-TO / TIPS',
    description: 'Practical step-by-step advice (Power BI technique, financial process, grant writing)',
    structure: ['Problem statement — the pain point',
      'Numbered steps or tips (3–5)',
      'One caveat or nuance',
      'Invitation to share their own approach'],
    bestFor: ['Power BI tutorials', 'financial processes', 'productivity hacks'],
    engagementMechanism: 'Saves/bookmarks + comments asking follow-up questions',
  },
  D: {
    code: 'D',
    name: 'PERSONAL STORY',
    description: 'Reflect on a real experience — cultural, leadership, career pivot',
    structure: ['Scene-setting sentence — specific moment in time',
      'What happened',
      'What you thought vs what you learned',
      'Universal lesson for the reader'],
    bestFor: ['career milestones', 'cultural insights', 'failure + recovery moments'],
    engagementMechanism: 'Authenticity drives comments and connection requests',
  },
  E: {
    code: 'E',
    name: 'SERIES CONTINUATION',
    description: 'Part of a 3–5 post series on a topic with legs',
    structure: ['Series label — "Part X of Y: [Series Title]"',
      'This post\'s specific angle',
      'Link back to previous part (text reference)',
      'Tease next part'],
    bestFor: ['deep-dive topics', 'multi-faceted issues', 'building return audience'],
    engagementMechanism: 'Followers who track the series become loyal readers',
  },
  F: {
    code: 'F',
    name: 'POLL / QUESTION',
    description: 'Engagement-first post to spark conversation and learn from audience',
    structure: ['Setup — why this question matters',
      'The question — clear, specific, provocative',
      'Poll options (if poll) or 2 contrasting positions',
      "Victor's lean (briefly stated)"],
    bestFor: ['low-content days', 'testing audience assumptions', 'building two-way relationships'],
    engagementMechanism: 'Algorithm rewards polls; comments reveal what the audience actually thinks',
  },
  G: {
    code: 'G',
    name: 'INDUSTRY DATA',
    description: "Present a statistic or finding with Victor's professional interpretation",
    structure: ['The stat — bold and specific',
      'Source and context',
      'What the number actually means (the interpretation)',
      'Call to action or question'],
    bestFor: ['economic data', 'industry surveys', 'government reports'],
    engagementMechanism: 'Data posts get reshared by people who want to look informed',
  },
  H: {
    code: 'H',
    name: 'CONTRARIAN TAKE',
    description: 'Challenge a common assumption in finance, BI, or NFP leadership',
    structure: ['State the common belief everyone holds',
      'Your contrarian position — stated clearly',
      'Evidence or reasoning',
      'Acknowledgment of the nuance / who is right in which context'],
    bestFor: ['overused advice', 'industry myths', 'consensus views worth questioning'],
    engagementMechanism: 'Disagreement drives comments; respectful contrarianism earns respect',
  },
};
