export const TOPIC_AREAS = [
  {
    id: 'aus_economy',
    label: 'Australian Business & Economy',
    weight: 9,
    searchQueries: [
      'RBA interest rate decision Australia 2025',
      'Australian federal budget 2025 business impact',
      'ASX market Australia news today',
      'Australian tax changes 2025 business',
      'ATO compliance update Australia',
      'Australian economy GDP inflation 2025',
    ],
    relevanceKeywords: ['RBA', 'ASX', 'ATO', 'Australia', 'budget', 'APRA', 'Treasury', 'CPI', 'inflation'],
  },
  {
    id: 'finance_accounting',
    label: 'Finance & Accounting',
    weight: 10,
    searchQueries: [
      'AASB accounting standards update Australia 2025',
      'NFP not-for-profit finance Australia 2025',
      'salary packaging FBT Australia 2025',
      'financial controller best practices 2025',
      'audit risk management Australia',
      'ACNC charity reporting requirements 2025',
      'NFP governance finance Australia',
    ],
    relevanceKeywords: ['AASB', 'ACNC', 'FBT', 'audit', 'NFP', 'charity', 'financial controller', 'IFRS'],
  },
  {
    id: 'power_bi_data',
    label: 'Power BI & Data Analytics',
    weight: 10,
    searchQueries: [
      'Power BI new features update 2025',
      'Microsoft Fabric analytics 2025',
      'DAX tips tricks Power BI 2025',
      'Power BI dashboard design best practices',
      'Power BI financial reporting template',
      'Microsoft Fabric vs Power BI 2025',
      'data analytics finance teams 2025',
    ],
    relevanceKeywords: ['Power BI', 'DAX', 'Microsoft Fabric', 'Power Query', 'dashboard', 'data model', 'report'],
  },
  {
    id: 'ai_automation',
    label: 'AI & Automation Tools',
    weight: 8,
    searchQueries: [
      'AI automation finance accounting 2025',
      'Claude AI business use cases 2025',
      'n8n workflow automation 2025',
      'AI agents finance teams 2025',
      'Excel Copilot finance automation',
      'automation tools small business Australia 2025',
    ],
    relevanceKeywords: ['AI', 'automation', 'Claude', 'GPT', 'n8n', 'Copilot', 'workflow', 'agent'],
  },
  {
    id: 'nfp_community',
    label: 'Jewish Community & Non-Profit Sector',
    weight: 7,
    searchQueries: [
      'NFP philanthropy Australia 2025',
      'Jewish community Australia news 2025',
      'charity fundraising trends Australia 2025',
      'community organisation governance Australia',
      'volunteer management NFP Australia',
      'DGR deductible gift recipient changes Australia',
    ],
    relevanceKeywords: ['philanthropy', 'Jewish', 'community', 'NFP', 'charity', 'fundraising', 'governance', 'DGR'],
  },
  {
    id: 'leadership_comms',
    label: 'Leadership, Communication & Persuasion',
    weight: 6,
    searchQueries: [
      'executive presence finance leaders 2025',
      'leadership communication skills 2025',
      'persuasion influence business 2025',
      'CFO leadership trends 2025',
      'workplace culture Australia 2025',
    ],
    relevanceKeywords: ['leadership', 'communication', 'executive', 'influence', 'culture', 'management', 'CFO'],
  },
];
